  version: "3.9"
  services:
    mysql:
      container_name: mysql
      image: mysql/mysql-server
      ports:
      - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=admin1
        - MYSQL_DATABASE=learning
      volumes:
        - ./docker/mysql/data:/var/lib/mysql
        - ./docker/mysql/init:/docker-entrypoint-initdb.d/:ro
    web:
      container_name: tomcat
      build: .
      ports:
        - "8080:8080"



