  version: 1
  services:
    mysql:
      container_name: mysql
      image: mysql/mysql-server
      ports:
      - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=mysql
        - MYSQL_DATABASE=db
      volumes:
      - ./database:/tmp/database
      command: mysqld --init-file="/tmp/database/install_db.sql"

